version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
      # - "5433:5432" local
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

  # runner:
  #   container_name: runner
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   volumes:
  #       - ./:/code
  #   depends_on:
  #     - postgres