version: '3'
services:
  postgres:
    # image: postgres:latest
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: totesys #testdb
      POSTGRES_USER: totesys #testuser
      POSTGRES_PASSWORD: totesys
    ports:
      - "5433:5432"
    volumes:
        # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./db:/docker-entrypoint-initdb.d
  #   healthcheck:
  #       test: ["CMD", "pg_isready", "-U", "totesys"]
  #       interval: 5s
  #       retries: 5
  #   restart: always

  # runner:
  #   container_name: runner
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   volumes:
  #       - ./:/code
  #   depends_on:
  #     - postgres