name: test-db
on: push
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Start psql container
        run: make up

      # - name: check psql is ready
      #   run: docker exec postgres pg_isready

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Run tests against the psql container
        run: make run-tests

